openapi: 3.0.0
info:
  version: "1.0.0"
  title: "e-Commerce Compra Fácil"
  description: |
    A API de integração do sistema **Compra Fácil** é um web service REST projetado para facilitar parcerias digitais por meio da exposição de dados de produtos e afiliados.
    Voltada para empresas que desejam integrar soluções como buscadores de preços, aplicativos de descontos e redes de afiliados, a API oferece recursos para busca, manipulação e ordenação de produtos, além do gerenciamento de afiliados.
    
    O objetivo desta API é ampliar o alcance da plataforma **Compra Fácil**, promovendo uma experiência de integração simplificada e robusta para parceiros comerciais, desenvolvedores e terceiros, contribuindo para a expansão do ecossistema digital.

    Benefícios:
    - **Busca de Produtos:** Filtros avançados por nome, categoria, faixa de preço e descontos.
    - **Ordenação Flexível:** Permite listar produtos por menor/maior preço, mais vendidos e lançamentos.
    - **Gestão de Afiliados:** Criar, editar, excluir e listar afiliados de forma intuitiva.

servers:
  - url: "https://localhost:3000"

paths:
  /products:
    get:
      tags:
        - PRODUTOS
      summary: Retorna uma lista de produtos com filtros, ordenação e paginação
      description: Permite buscar, filtrar e ordenar produtos por diversos critérios.
      parameters:
        - name: name
          in: query
          description: Nome parcial ou completo do produto
          required: false
          schema:
            type: string
        - name: category
          in: query
          description: Categoria do produto
          required: false
          schema:
            type: string
        - name: min_price
          in: query
          description: Preço mínimo
          required: false
          schema:
            type: number
            format: float
        - name: max_price
          in: query
          description: Preço máximo
          required: false
          schema:
            type: number
            format: float
        - name: on_discount
          in: query
          description: Filtrar apenas produtos com desconto
          required: false
          schema:
            type: boolean
        - name: sort
          in: query
          description: Ordenação dos resultados (pode ser combinado com asc ou desc)
          required: false
          schema:
            type: string
            enum: [price, sales, release_date]
        - name: order
          in: query
          description: Direção da ordenação (ascendente ou descendente)
          required: false
          schema:
            type: string
            enum: [asc, desc]
        - name: page
          in: query
          description: Número da página para a paginação
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          description: Quantidade de produtos por página
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Lista de produtos retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total de produtos encontrados
                  page:
                    type: integer
                    description: Página atual
                  page_size:
                    type: integer
                    description: Tamanho da página atual
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ID do produto
                        name:
                          type: string
                          description: Nome do produto
                        category:
                          type: string
                          description: Categoria do produto
                        price:
                          type: number
                          format: float
                          description: Preço do produto
                        sales:
                          type: integer
                          description: Quantidade de vendas
                        release_date:
                          type: string
                          format: date
                          description: Data de lançamento
                        discount:
                          type: number
                          format: float
                          description: Porcentagem de desconto
        '429':
          description: Número de chamadas excedido
        '500':
          description: Erro interno do servidor
  
    post:
      tags:
        - PRODUTOS
      summary: Cria um novo produto
      description: Endpoint para criar um novo produto com os campos necessários.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - category
                - price
                - release_date
              properties:
                name:
                  type: string
                  description: Nome do produto
                  example: "Smartphone Z"
                category:
                  type: string
                  description: Categoria do produto
                  example: "Eletrônicos"
                description:
                  type: string
                  description: Descrição do produto
                  example: "Smartphone de última geração com câmera de 108 MP."
                price:
                  type: number
                  format: float
                  description: Preço do produto
                  example: 1999.99
                discount:
                  type: number
                  format: float
                  description: Porcentagem de desconto (opcional)
                  example: 10.0
                release_date:
                  type: string
                  format: date
                  description: Data de lançamento do produto
                  example: "2024-01-15"
                sales:
                  type: integer
                  description: Número inicial de vendas (opcional)
                  example: 0
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID do produto criado
                    example: "12345"
                  name:
                    type: string
                    description: Nome do produto
                    example: "Smartphone Z"
                  category:
                    type: string
                    description: Categoria do produto
                    example: "Eletrônicos"
                  price:
                    type: number
                    format: float
                    description: Preço do produto
                    example: 1999.99
                  discount:
                    type: number
                    format: float
                    description: Porcentagem de desconto
                    example: 10.0
                  release_date:
                    type: string
                    format: date
                    description: Data de lançamento do produto
                    example: "2024-01-15"
        '400':
          description: Requisição inválida (validação falhou)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensagem de erro detalhando a falha de validação
                    example: "O campo 'name' é obrigatório."
        '429':
          description: Muitas requisições
        '500':
          description: Erro interno
  
  /products/{id}:
    get:
      tags:
        - PRODUTOS
      summary: Retorna um produto pelo ID
      description: Recupera os detalhes de um produto específico.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto a ser recuperado.
          schema:
            type: string
      responses:
        '200':
          description: Produto retornado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  category:
                    type: string
                  price:
                    type: number
        '404':
          description: Produto não encontrado
        '500':
          description: Erro interno
        

    put:
      tags:
        - PRODUTOS
      summary: Atualiza um produto pelo ID
      description: Atualiza as informações de um produto existente.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto a ser atualizado.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nome do produto
                category:
                  type: string
                  description: Categoria do produto
                price:
                  type: number
                  description: Preço do produto
      responses:
        '200':
          description: Produto atualizado com sucesso
        '400':
          description: Requisição inválida
        '404':
          description: Produto não encontrado
        '500':
          description: Erro interno

    delete:
      tags:
        - PRODUTOS
      summary: Remove um produto pelo ID
      description: Exclui um produto existente.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto a ser excluído.
          schema:
            type: string
      responses:
        '204':
          description: Produto excluído com sucesso
        '404':
          description: Produto não encontrado
        '500':
          description: Erro interno
      

  /afiliados:
    get:
      tags:
        - AFILIADOS
      summary: Lista de afiliados com filtros
      description: Recupera uma lista de afiliados com base em filtros como status ou nome.
      parameters:
        - name: status
          in: query
          description: Filtra afiliados pelo status (ativo ou inativo)
          required: false
          schema:
            type: string
            enum: [ativo, inativo]
        - name: name
          in: query
          description: Nome parcial ou completo do afiliado
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista de afiliados retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total de afiliados encontrados
                  afiliados:
                    type: array
                    items:
                      $ref: '#/components/schemas/afiliado'
        '500':
          description: Erro interno do servidor

    post:
      tags:
        - AFILIADOS
      summary: Cria um novo afiliado
      description: Registra um novo afiliado no sistema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - phone
              properties:
                name:
                  type: string
                  description: Nome do afiliado
                  example: "João Silva"
                email:
                  type: string
                  description: Email do afiliado
                  example: "joao.silva@example.com"
                phone:
                  type: string
                  description: Telefone do afiliado
                  example: "+5511999999999"
                website:
                  type: string
                  description: Website do afiliado (opcional)
                  example: "https://joaosilva.com"
      responses:
        '201':
          description: Afiliado criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/afiliado'
        '400':
          description: Requisição inválida
        '500':
          description: Erro interno do servidor

  /afiliados/{id}:
    get:
      tags:
        - AFILIADOS
      summary: Recupera um afiliado pelo ID
      description: Retorna os detalhes de um afiliado específico.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do afiliado a ser recuperado.
          schema:
            type: string
      responses:
        '200':
          description: Afiliado retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/afiliado'
        '404':
          description: Afiliado não encontrado
        '500':
          description: Erro interno do servidor

    put:
      tags:
        - AFILIADOS
      summary: Atualiza um afiliado pelo ID
      description: Atualiza as informações de um afiliado existente.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do afiliado a ser atualizado.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nome do afiliado
                email:
                  type: string
                  description: Email do afiliado
                phone:
                  type: string
                  description: Telefone do afiliado
                website:
                  type: string
                  description: Website do afiliado
                status:
                  type: string
                  description: Status do afiliado
                  enum: [ativo, inativo]
      responses:
        '200':
          description: Afiliado atualizado com sucesso
        '400':
          description: Requisição inválida
        '404':
          description: Afiliado não encontrado
        '500':
          description: Erro interno do servidor

    delete:
      tags:
        - AFILIADOS
      summary: Remove um afiliado pelo ID
      description: Exclui um afiliado existente.
      parameters:
        - name: id
          in: path
          required: true
          description: ID do afiliado a ser excluído.
          schema:
            type: string
      responses:
        '204':
          description: Afiliado excluído com sucesso
        '404':
          description: Afiliado não encontrado
        '500':
          description: Erro interno do servidor

components:
  securitySchemes:
    ApiKeyAuthId:
      type: apiKey
      in: header
      name: x-api-key-id

  schemas:
    produto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
        price:
          type: number
        sales:
          type: integer
        release_date:
          type: string
          format: date
        discount:
          type: number
          format: float

    afiliado:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        website:
          type: string
        status:
          type: string
          enum: [ativo, inativo]

security:
  - ApiKeyAuthId: []